# Generated by Django 5.1.15 on 2026-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_razorpaywebhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaywebhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("processed", "Processed"),
                    ("unknown_transaction", "Unknown transaction"),
                    ("amount_mismatch", "Amount mismatch"),
                    ("currency_mismatch", "Currency mismatch"),
                    ("payment_id_mismatch", "Payment ID mismatch"),
                    ("ignored_event_type", "Ignored event type"),
                    ("error", "Error"),
                ],
                db_index=True,
                max_length=24,
                verbose_name="Status",
            ),
        ),
    ]
