# Generated by Django 5.1.15 on 2026-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_yarn_guy_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Yarn Guy', max_length=120),
        ),
    ]
