# Generated by Django 5.1.15 on 2026-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sitesettings_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_shipping_charge',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cod_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='COD Delivery Charge'),
        ),
    ]
