# Generated by Django 5.1.15 on 2026-08-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelhiveryShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('waybill_number', models.CharField(blank=True, help_text='Tracking number provided by Delhivery.', max_length=100, null=True, verbose_name='Waybill Number')),
                ('tracking_status', models.CharField(db_index=True, default='Initiated', max_length=100, verbose_name='Tracking Status')),
                ('label_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Label URL')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message / Logs')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delhivery_shipment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delhivery Shipment',
                'verbose_name_plural': 'Delhivery Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
