# Generated by Django 5.1.15 on 2026-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_wholesaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Deliverable city for this address.', max_length=120, verbose_name='City'),
        ),
    ]
