# Generated by Django 5.1.15 on 2026-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, default='', help_text='6-digit PIN code for shipping.', max_length=20, verbose_name='PIN / Postal code'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='State / Province'),
        ),
    ]
