# Generated by Django 5.1.15 on 2026-08-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address_pincode_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='notify_via_sms',
            field=models.BooleanField(default=False, help_text='Receive order updates via SMS.', verbose_name='SMS notifications'),
        ),
    ]
