# Generated by Django 5.1.15 on 2026-08-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_wholesale_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base price'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Purchase Price'),
        ),
    ]
