# Generated by Django 5.1.15 on 2026-08-03 17:07

from django.db import migrations

def update_variant_prices(apps, schema_editor):
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    for variant in ProductVariant.objects.select_related('product').all():
        variant.base_price = variant.product.base_price + variant.price_delta
        variant.mrp = variant.product.mrp
        variant.purchase_price = variant.product.purchase_price
        # if the variant had stock, keep it. threshold defaults to 5
        variant.save(update_fields=['base_price', 'mrp', 'purchase_price'])

def reverse_update(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productvariant_base_price_productvariant_mrp_and_more'),
    ]

    operations = [
        migrations.RunPython(update_variant_prices, reverse_update),
    ]
