# Generated by Django 5.1.15 on 2026-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_update_variant_prices_from_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price_delta',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='Low stock threshold'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Variant Name'),
        ),
    ]
