# Generated by Django 5.1.15 on 2026-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_productvariant_price_delta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku_suffix',
            field=models.CharField(blank=True, help_text='Appended to the parent product SKU.', max_length=32, verbose_name='SKU suffix'),
        ),
    ]
