# Generated by Django 5.1.15 on 2026-08-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_productvariant_sku_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('is_shown', models.BooleanField(db_index=True, default=False, verbose_name='Is shown on home')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_featured', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Home Page Product',
                'verbose_name_plural': 'Home Page Products',
                'ordering': ['-updated_at'],
            },
        ),
    ]
