# Generated by Django 5.1.15 on 2026-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_homepageproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='e.g., 2.5 kg, 12V, Lithium-Ion', max_length=1024, verbose_name='Specification Value'),
        ),
    ]
