# Generated by Django 5.1.15 on 2026-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_productspecification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters.', max_digits=8, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters.', max_digits=8, null=True, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kilograms, used for courier booking.', max_digits=8, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width (breadth) in centimeters.', max_digits=8, null=True, verbose_name='Width (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override product height.', max_digits=8, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override product length.', max_digits=8, null=True, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Override product weight.', max_digits=8, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override product width.', max_digits=8, null=True, verbose_name='Width (cm)'),
        ),
    ]
