# Generated by Django 5.1.15 on 2026-08-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_height_product_length_product_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='length',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='width',
        ),
    ]
