# Generated by Django 5.1.15 on 2026-08-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_productvariant_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('name', models.CharField(help_text="Internal name to identify the size chart (e.g., 'Men T-Shirts').", max_length=120, verbose_name='Name')),
                ('content_html', models.TextField(blank=True, help_text='Rich text or HTML table for the size chart.', verbose_name='Content (HTML/Table)')),
                ('image', models.ImageField(blank=True, help_text='Optional fallback image. Used if no rich text content is provided.', null=True, upload_to='size_charts/', verbose_name='Fallback Image')),
            ],
            options={
                'verbose_name': 'Size Chart',
                'verbose_name_plural': 'Size Charts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.sizechart', verbose_name='Size Chart'),
        ),
    ]
