# Generated by Django 5.1.15 on 2026-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_sizechart_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='When False, size chart is hidden from the product selection dropdown.', verbose_name='Is active'),
        ),
    ]
