# Generated by Django 5.1.15 on 2026-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_sizechart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizechart',
            name='content_html',
            field=models.TextField(blank=True, help_text='Use the table tool to create your size chart grid.', verbose_name='Content'),
        ),
    ]
