# Generated by Django 5.1.15 on 2026-09-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_sizechart_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='Harmonized System of Nomenclature code.', max_length=255, null=True, verbose_name='HSN Code'),
        ),
    ]
