# Generated by Django 5.1.15 on 2026-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_product_hsn_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Drives the product's displayed price/stock when variants exist.",
                verbose_name="Default variant",
            ),
        ),
    ]
