# Generated by Django 5.1.15 on 2026-08-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_phase10_performance_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='destination_city',
        ),
    ]
