# Generated by Django 5.1.15 on 2026-09-17 18:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_variant_snapshot(apps, schema_editor):
    """
    Populate variant_name/variant_sku on existing OrderItem rows from their
    still-live variant FK. Rows whose variant was already deleted (variant_id
    already NULL, under the old SET_NULL behavior) have nothing to backfill
    from and are left blank — that history is unrecoverable.
    """
    OrderItem = apps.get_model("orders", "OrderItem")
    items = OrderItem.objects.filter(variant__isnull=False).select_related("variant", "product")
    updated = []
    for item in items:
        item.variant_name = item.variant.name
        item.variant_sku = f"{item.product.sku}-{item.variant.sku_suffix}" if item.variant.sku_suffix else item.product.sku
        updated.append(item)
    if updated:
        OrderItem.objects.bulk_update(updated, ["variant_name", "variant_sku"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_productvariant_is_default"),
        ("orders", "0009_picked_up_in_transit_out_for_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Captured at purchase time so history survives a later variant edit/delete.",
                max_length=120,
                verbose_name="Variant name (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_sku",
            field=models.CharField(
                blank=True, default="", max_length=96, verbose_name="Variant SKU (snapshot)"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.productvariant",
                verbose_name="Variant",
            ),
        ),
        migrations.RunPython(backfill_variant_snapshot, migrations.RunPython.noop),
    ]
