# Generated by Django 5.1.15 on 2026-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customerprofile_notify_via_sms"),
        ("cart", "0003_remove_cart_destination_city"),
        ("core", "0019_sitesettings_order_notification_email"),
        ("orders", "0010_orderitem_variant_name_orderitem_variant_sku_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="ord_customer_created_idx",
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_profile", "-updated_at"], name="ord_customer_updated_idx"
            ),
        ),
    ]
