# Generated by Django 5.1.15 on 2026-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customerprofile_notify_via_sms"),
        ("cart", "0003_remove_cart_destination_city"),
        ("core", "0019_sitesettings_order_notification_email"),
        ("orders", "0011_order_sort_by_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": [
                    models.OrderBy(models.F("success_at"), descending=True, nulls_last=True),
                    "-created_at",
                ],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="ord_customer_updated_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="success_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this order first became a real sale: online payment confirmed, or COD order placed. Null for CHECKOUT_PENDING orders that never succeeded. Set once in orders.services.transition_order_status (CONFIRMED/PLACED_COD) and at direct COD creation in checkout.services.place_order — never touched again, unlike updated_at, so later unrelated changes (a courier scan, an address edit) can't move an order's position by accident.",
                null=True,
                verbose_name="Order success at",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_profile", "-success_at"], name="ord_customer_success_idx"
            ),
        ),
    ]
