# Generated by Django 5.1.15 on 2026-10-06 14:50

from django.db import migrations


def backfill_success_at(apps, schema_editor):
    """
    Best-effort historical success_at for orders that already moved past
    CHECKOUT_PENDING before this field existed.

    Preferred source: the earliest OrderStatusHistory row recording the order
    reaching CONFIRMED or PLACED_COD (covers online-payment success and an
    existing order switched to COD, both of which go through
    orders.services.transition_order_status). Orders placed directly as COD
    never had a transition recorded for that first status, so they fall back to
    created_at — an exact match, since success happens at creation for them.
    CHECKOUT_PENDING orders are left with success_at = NULL: they never
    succeeded, so there is nothing to backfill.
    """
    Order = apps.get_model("orders", "Order")
    OrderStatusHistory = apps.get_model("orders", "OrderStatusHistory")

    orders = Order.objects.exclude(order_status="checkout_pending").only(
        "id", "created_at"
    )
    for order in orders.iterator():
        history = (
            OrderStatusHistory.objects.filter(
                order_id=order.id, to_status__in=["confirmed", "placed_cod"]
            )
            .order_by("changed_at")
            .first()
        )
        order.success_at = history.changed_at if history else order.created_at
        order.save(update_fields=["success_at"])


def noop_reverse(apps, schema_editor):
    """Nothing to reverse — success_at is simply dropped by the previous migration."""


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_success_at"),
    ]

    operations = [
        migrations.RunPython(backfill_success_at, noop_reverse),
    ]
